// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aymnyszcqpzdgvdqlzhg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5bW55c3pjcXB6ZGd2ZHFsemhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0ODA2MzUsImV4cCI6MjA2MzA1NjYzNX0.QUJxxXEkjLSalM4ms3ZowrQyJihPf-wP2mBLFkv4BxI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);